/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.unjfsc.fsi.java8.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pe.unjfsc.fsi.java8.entity.CEVehiculo;
import pe.unjfsc.fsi.java8.logical.impl.CMColor;
import pe.unjfsc.fsi.java8.logical.impl.CMMarca;
import pe.unjfsc.fsi.java8.logical.impl.CMTipoVehiculo;
import pe.unjfsc.fsi.java8.logical.impl.CMVehiculo;

/**
 *
 * @author Hugo Grados
 */
public class JInternalVehiculo extends javax.swing.JInternalFrame {

    int xidVehiculo;
    int xidMarca;
    int xidColor;
    int xidTipo;
    DefaultTableModel objDtm;
    ResultSet rsVehiculo;
    ResultSet rsColor;
    ResultSet rsTipo;
    boolean sw;
    ResultSet rsMarca;
    CMVehiculo objCLVehiculo = new CMVehiculo();
    CMMarca objCLMarca = new CMMarca();
    CMColor objCLColor = new CMColor();
    CMTipoVehiculo objCLTipo = new CMTipoVehiculo();

    /**
     * Creates new form JInternalVehiculo
     */
    public JInternalVehiculo() {
        initComponents();
        objDtm = (DefaultTableModel) tablaVehiculo.getModel();
        setVisible(true);
        llenaComboMarca();
        llenaComboTipo();
        llenacomboColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnGuardar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculo = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtSerie = new javax.swing.JTextField();
        jcmbMarca = new javax.swing.JComboBox<>();
        jcmbcolor = new javax.swing.JComboBox<>();
        jcmbCarga = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jtxtLlantas = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtxtPBruto = new javax.swing.JTextField();
        jtxtPNeto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxtPUtil = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtPlaca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jtxtBuscar = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("BUSCAR:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar.png"))); // NOI18N
        jbtnGuardar.setText("GUARDAR");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 120, 50));

        jbtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eliminarVehiculo.png"))); // NOI18N
        jbtnEliminar.setText("ELIMINAR");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 120, 50));

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelarRegistro.png"))); // NOI18N
        jbtnCancelar.setText("CANCELAR");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, 50));

        jbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        jbtnEditar.setText("EDITAR");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 120, 50));

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registroNuevo.png"))); // NOI18N
        jbtnNuevo.setText("NUEVO");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 130, 50));

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 120, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 710, 130));

        tablaVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PLACA", "SERIE", "MARCA", "COLOR", "TIPO", "LLANTAS", "P. BRUTO", "P. NETO", "P.UTIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVehiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVehiculo);
        if (tablaVehiculo.getColumnModel().getColumnCount() > 0) {
            tablaVehiculo.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 710, 140));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setText("VEHICULO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel7.setText("MARCA");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel8.setText("TIPO CARGA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel9.setText("COLOR");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel10.setText("NRO SERIE");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jtxtSerie.setEditable(false);
        jPanel2.add(jtxtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 230, 31));

        jcmbMarca.setEnabled(false);
        jcmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbMarcaActionPerformed(evt);
            }
        });
        jPanel2.add(jcmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 230, 30));

        jcmbcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE COLOR" }));
        jcmbcolor.setEnabled(false);
        jcmbcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbcolorActionPerformed(evt);
            }
        });
        jPanel2.add(jcmbcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 230, 30));

        jcmbCarga.setEnabled(false);
        jcmbCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCargaActionPerformed(evt);
            }
        });
        jPanel2.add(jcmbCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 230, 30));

        jLabel15.setText("NRO LLANTAS");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jtxtLlantas.setEditable(false);
        jPanel2.add(jtxtLlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, 31));

        jLabel16.setText("PESO BRUTO");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jtxtPBruto.setEditable(false);
        jPanel2.add(jtxtPBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 230, 31));

        jtxtPNeto.setEditable(false);
        jPanel2.add(jtxtPNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 230, 31));

        jLabel17.setText("PESO NETO");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jtxtPUtil.setEditable(false);
        jPanel2.add(jtxtPUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 230, 31));

        jLabel18.setText("PESO UTIL");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jtxtPlaca.setEditable(false);
        jPanel2.add(jtxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, 32));

        jLabel12.setText("PLACA");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jtxtId.setEditable(false);
        jtxtId.setEnabled(false);
        jPanel2.add(jtxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 230, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 710, 230));

        jtxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 200, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        try {
            String mensaje = "";
            CEVehiculo objVehiculoCE = new CEVehiculo();
            //objVehiculoCE.setIdVehiculo(xidVehiculo);
            objVehiculoCE.setPlaca(jtxtPlaca.getText().toUpperCase());
            objVehiculoCE.setNroSerie(jtxtSerie.getText().toUpperCase());
            xidMarca = obtenerIdMarca();
            objVehiculoCE.setMarca(xidMarca);
            xidColor = obtenerIdColor();
            objVehiculoCE.setColor(xidColor);
            xidTipo = obtenerIdTipo();
            objVehiculoCE.setTipoCarga(xidTipo);
            objVehiculoCE.setNroLlantas(Integer.parseInt(jtxtLlantas.getText().toUpperCase()));
            objVehiculoCE.setPeso_bruto(Integer.parseInt(jtxtPBruto.getText().toUpperCase()));
            objVehiculoCE.setPeso_neto(Integer.parseInt(jtxtPNeto.getText().toUpperCase()));
            objVehiculoCE.setPeso_util(Integer.parseInt(jtxtPUtil.getText().toUpperCase()));
            if (sw) {
                objCLVehiculo.insert(objVehiculoCE);
                mensaje = "Registro grabado";
            } else {
                xidVehiculo = Integer.parseInt(jtxtId.getText());
                objVehiculoCE.setIdVehiculo(xidVehiculo);
                objCLVehiculo.update(objVehiculoCE);
                mensaje = "Registro actualizado";
            }
            habilitaControles(false);
            JOptionPane.showMessageDialog(rootPane, mensaje);
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        try {
            int op = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea eliminar?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (op == JOptionPane.YES_OPTION) {
                CEVehiculo objVehiculoTO = new CEVehiculo();
                objVehiculoTO.setIdVehiculo(Integer.parseInt(jtxtId.getText()));
                objCLVehiculo.delete(objVehiculoTO);
                limpiarControles();
                JOptionPane.showMessageDialog(rootPane, "Registro Borrado");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        habilitaControles(false);
        limpiarControles();    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        habilitaControles(true);
        sw = false;
        llenaComboMarca();
        llenaComboTipo();
        llenacomboColor();
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        habilitaControles(true);
        limpiarControles();
        sw = true;
        llenaComboMarca();
        llenacomboColor();
        llenaComboTipo();
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void tablaVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVehiculoMouseClicked
        try {
            xidVehiculo = Integer.parseInt(tablaVehiculo.getValueAt(tablaVehiculo.getSelectedRow(), 0).toString());
            rsVehiculo.first();
            do {
                if (xidVehiculo == rsVehiculo.getInt(1)) {
                    jtxtId.setText(String.valueOf(rsVehiculo.getInt(1)));
                    jtxtPlaca.setText((rsVehiculo.getString(2)));
                    jtxtSerie.setText(rsVehiculo.getString(3));
                    jcmbMarca.removeAllItems();
                    jcmbMarca.addItem(rsVehiculo.getString(4));
                    jcmbcolor.removeAllItems();
                    jcmbcolor.addItem(rsVehiculo.getString(5));
                    jcmbCarga.removeAllItems();
                    jcmbCarga.addItem(rsVehiculo.getString(6));
                    jtxtLlantas.setText(String.valueOf(rsVehiculo.getInt(7)));
                    jtxtPBruto.setText(String.valueOf(rsVehiculo.getInt(8)));
                    jtxtPNeto.setText(String.valueOf(rsVehiculo.getInt(9)));
                    jtxtPUtil.setText(String.valueOf(rsVehiculo.getInt(10)));
                    rsVehiculo.last();
                }
            } while (rsVehiculo.next());
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tablaVehiculoMouseClicked

    private void jcmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbMarcaActionPerformed
    }//GEN-LAST:event_jcmbMarcaActionPerformed

    private void jcmbcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbcolorActionPerformed

    private void jcmbCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCargaActionPerformed

    }//GEN-LAST:event_jcmbCargaActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jtxtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyReleased
        try {
            limpiarJTable();
            if (!jtxtBuscar.getText().isEmpty()) {
                rsVehiculo = objCLVehiculo.buscar(jtxtBuscar.getText().trim());
                while (rsVehiculo.next()) {
                    Object registro[] = {rsVehiculo.getInt(1), rsVehiculo.getString(2), rsVehiculo.getString(3),
                        rsVehiculo.getString(4), rsVehiculo.getString(5), rsVehiculo.getString(6), rsVehiculo.getInt(7),
                        rsVehiculo.getInt(8), rsVehiculo.getInt(9), rsVehiculo.getInt(10)};
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }    }//GEN-LAST:event_jtxtBuscarKeyReleased
    private void llenaComboTipo() {
        try {
            rsTipo = objCLTipo.buscar("%");
            while (rsTipo.next()) {
                jcmbCarga.addItem(rsTipo.getString(2));
            }
        } catch (Exception e) {
        }
    }

    private void llenacomboColor() {
        try {
            rsColor = objCLColor.buscar("%");
            while (rsColor.next()) {
                jcmbcolor.addItem(rsColor.getString(2));
            }
        } catch (Exception e) {
        }
    }

    private void llenaComboMarca() {
        try {
            rsMarca = objCLMarca.buscar("%");
            while (rsMarca.next()) {
                jcmbMarca.addItem(rsMarca.getString(2));
            }
        } catch (Exception e) {
        }
    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) { // RECORRE LA TABLA
            objDtm.removeRow(0);
        }
    }

    private void habilitaControles(boolean b) {
        jbtnNuevo.setEnabled(!b);
        jtxtPlaca.setEditable(b);
        jtxtSerie.setEditable(b);
        jtxtLlantas.setEditable(b);
        jtxtPBruto.setEditable(b);
        jtxtPNeto.setEditable(b);
        jtxtPUtil.setEditable(b);
        jcmbMarca.setEnabled(b);
        jcmbcolor.setEnabled(b);
        jcmbCarga.setEnabled(b);
        jbtnGuardar.setEnabled(b);
        jbtnCancelar.setEnabled(b);
        jbtnEliminar.setEnabled(b);
        jbtnEditar.setEnabled(!b);
    }

    private void limpiarControles() {
        JTextField[] arrJTextFields = {jtxtId, jtxtPlaca, jtxtSerie, jtxtBuscar, jtxtLlantas, jtxtPBruto,
            jtxtPNeto, jtxtPUtil};
        for (JTextField objJTextField : arrJTextFields) {
            objJTextField.setText(null);
        }
        limpiarJTable();
        jcmbMarca.removeAllItems();
        jcmbCarga.removeAllItems();
        jcmbcolor.removeAllItems();
    }

    private int obtenerIdMarca() {
        int xcodMarca = 0;
        try {
            String nombre = jcmbMarca.getSelectedItem().toString();
            rsMarca.first();
            do {
                
                if (nombre.equals(rsMarca.getString(2))) {
                    xcodMarca = rsMarca.getInt(1);
                    rsMarca.last();
                }
            } while (rsMarca.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return xcodMarca;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcmbCarga;
    private javax.swing.JComboBox<String> jcmbMarca;
    private javax.swing.JComboBox<String> jcmbcolor;
    private javax.swing.JTextField jtxtBuscar;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtLlantas;
    private javax.swing.JTextField jtxtPBruto;
    private javax.swing.JTextField jtxtPNeto;
    private javax.swing.JTextField jtxtPUtil;
    private javax.swing.JTextField jtxtPlaca;
    private javax.swing.JTextField jtxtSerie;
    private javax.swing.JTable tablaVehiculo;
    // End of variables declaration//GEN-END:variables

    private int obtenerIdColor() {
        int xcodColor = 0;
        try {
            String nombre = jcmbcolor.getSelectedItem().toString();
            rsColor.first();
            do {
                if (nombre.equals(rsColor.getString(2))) {
                    xcodColor = rsColor.getInt(1);
                    rsColor.last();
                }
            } while (rsColor.next());
        } catch (Exception e) {
        }
        return xcodColor;
    }

    private int obtenerIdTipo() {
        int xcodTipo = 0;
        try {
            String nombre = jcmbCarga.getSelectedItem().toString();
            rsTipo.first();
            do {
                if (nombre.equals(rsTipo.getString(2))) {
                    xcodTipo = rsTipo.getInt(1);
                    rsTipo.last();
                }
            } while (rsTipo.next());
        } catch (Exception e) {
        }
        return xcodTipo;
    }
}
