/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.unjfsc.fsi.java8.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.unjfsc.fsi.java8.logical.impl.CMConductor;

/**
 *
 * @author MIRKO
 */
public class JInternalBuscarConductor extends javax.swing.JInternalFrame {
    DefaultTableModel objDtm;
    ResultSet rsConductor;
    CMConductor objConductorDAO = new CMConductor();
    /**
     * Creates new form JInternalBuscarConductor
     */
    public JInternalBuscarConductor() {
        initComponents();
        objDtm = (DefaultTableModel) jtblRegistros.getModel();
        setSize(529, 299);
        setLocation(800, 50);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtbuscar_conductor = new javax.swing.JTextField();
        btnagregar_conductor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistros = new javax.swing.JTable();
        jbtnSalir = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Buscar Conductor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 140, 19);

        jtxtbuscar_conductor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbuscar_conductorKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtbuscar_conductor);
        jtxtbuscar_conductor.setBounds(180, 50, 220, 22);

        btnagregar_conductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conductor.png"))); // NOI18N
        btnagregar_conductor.setText("Agregar Conductor");
        btnagregar_conductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_conductorActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar_conductor);
        btnagregar_conductor.setBounds(140, 90, 200, 50);

        jtblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblRegistros);
        if (jtblRegistros.getColumnModel().getColumnCount() > 0) {
            jtblRegistros.getColumnModel().getColumn(0).setResizable(false);
            jtblRegistros.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 452, 90);

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSalir);
        jbtnSalir.setBounds(360, 90, 96, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregar_conductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_conductorActionPerformed
      try {
//            JInternalEnvio.jtxtid_conductor.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 0).toString());
//            JInternalEnvio.jtxtdni_conductor.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 1).toString());
//           
        } catch (Exception e) {
        }  // TODO add your handling code here:
    }//GEN-LAST:event_btnagregar_conductorActionPerformed

    private void jtxtbuscar_conductorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbuscar_conductorKeyReleased
       try {
            limpiarJTable();
            if (!jtxtbuscar_conductor.getText().isEmpty()) {
                rsConductor = objConductorDAO.buscar(jtxtbuscar_conductor.getText().trim());
                while (rsConductor.next()) {
                    Object registro[] = {rsConductor.getInt(1), rsConductor.getString(2), rsConductor.getString(4), rsConductor.getString(5), rsConductor.getString(7)};
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jtxtbuscar_conductorKeyReleased

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
       dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSalirActionPerformed
      private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar_conductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JTable jtblRegistros;
    private javax.swing.JTextField jtxtbuscar_conductor;
    // End of variables declaration//GEN-END:variables
}
