/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.unjfsc.fsi.java8.view;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.unjfsc.fsi.java8.entity.CERegistroAsig;
import pe.unjfsc.fsi.java8.logical.impl.CMConductor;
import pe.unjfsc.fsi.java8.logical.impl.CMRegistro;
import pe.unjfsc.fsi.java8.logical.impl.CMRegistroAsig;
import pe.unjfsc.fsi.java8.logical.impl.CMVehiculo;

/**
 *
 * @author Hugo Grados
 */
public class JInternalEnvioAceptado extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalEnvioAceptado
     */
    ResultSet rsRegistro;
    DefaultTableModel objDtm;
    CMRegistro objCMRegistro = new CMRegistro();
    ResultSet rsConductor;
    ResultSet rsVehiculo;
    CMConductor objCMConductor = new CMConductor();
    CMVehiculo objCMVehiculo = new CMVehiculo();
    CMRegistroAsig objCMRegistroAsig = new CMRegistroAsig();
    SimpleDateFormat objSimpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");

    boolean sw;
    int xidcodigo;

    public JInternalEnvioAceptado() {
        initComponents();
        objDtm = (DefaultTableModel) tablaaceptados.getModel();
        setVisible(true);
        setSize(962, 513);
        setTitle("ASIGNACIÓN DE CONDUCTORES");
        llenaComboConductor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnMostarEnvios = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtnAnular = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();
        jcmbConductor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtxtidRegistro = new javax.swing.JTextField();
        jbtnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtidPeso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaaceptados = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ENVIOS ACEPTADOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jbtnMostarEnvios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        jbtnMostarEnvios.setText("MOSTRAR ENVIOS");
        jbtnMostarEnvios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostarEnviosActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMostarEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 240, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("FECHA DE PARTIDA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 200, 20));

        jbtnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelarRegistro.png"))); // NOI18N
        jbtnAnular.setText("CANCELAR");
        jbtnAnular.setEnabled(false);
        jbtnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnularActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 140, 50));

        jbtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar_1.png"))); // NOI18N
        jbtnAceptar.setText("ASIGNAR");
        jbtnAceptar.setEnabled(false);
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 130, 50));

        jcmbConductor.setEnabled(false);
        jcmbConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbConductorActionPerformed(evt);
            }
        });
        jPanel1.add(jcmbConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 250, 30));

        jLabel3.setText("ID REGISTRO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));
        jPanel1.add(jtxtidRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 60, 30));

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida.png"))); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 160, 50));

        jLabel4.setText("PESO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));
        jPanel1.add(jtxtidPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 60, 30));

        jLabel6.setText("SELECCIONE AL CONDUCTOR:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 200, 20));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 890, 210));

        jLabel5.setText("ASIGNACION A ENVIOS ACEPTADOS SIN CONDUCTOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        tablaaceptados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID REGISTRO", "AP CLIENTE", "AM CLIENTE", "PESO", "PAQUETES", "DESCRIPCION", "DPTO PARTIDA", "DPTO LLEGADA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaaceptados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaaceptadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaaceptados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 890, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMostarEnviosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostarEnviosActionPerformed
        limpiarJTable();
        try {
            rsRegistro = objCMRegistro.buscar_registros_aceptados();
            while (rsRegistro.next()) {
                Object registro[] = {rsRegistro.getInt(1), rsRegistro.getString(2), rsRegistro.getString(3), rsRegistro.getDouble(4), rsRegistro.getInt(5),
                    rsRegistro.getString(6), rsRegistro.getString(7), rsRegistro.getString(8)};
                objDtm.addRow(registro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
        habilitarControles(true);
    }//GEN-LAST:event_jbtnMostarEnviosActionPerformed

    private void jbtnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnularActionPerformed
        habilitarControles(false);
        limpiarControles();
    }//GEN-LAST:event_jbtnAnularActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        sw = true;
        int xidConductor;
        try {
            String mensaje = "";
            CERegistroAsig objCERegistroAsig = new CERegistroAsig();
            objCERegistroAsig.setIdRegistro(Integer.parseInt(jtxtidRegistro.getText().toUpperCase()));
            xidConductor = obtenerIdConductor();
            objCERegistroAsig.setIdConductor(xidConductor);
            java.util.Date fecha = (jDateChooser1.getDate());
            java.sql.Date fechaPärtida = new java.sql.Date(fecha.getTime());
            objCERegistroAsig.setFechaPartida(fechaPärtida);       
            objCMRegistroAsig.update(objCERegistroAsig);
            mensaje = "CONDUCTOR ASIGNADO";
            JOptionPane.showMessageDialog(this, mensaje);
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getCause());
        }
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jcmbConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbConductorActionPerformed

    }//GEN-LAST:event_jcmbConductorActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void tablaaceptadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaaceptadosMouseClicked
        try {
            int fila_seleccionada = tablaaceptados.getSelectedRow();
            //LOS DATOS DE LA FILA SELECCIONADA LOS ENVIAMOS A LAS CADENAS DE TEXTO
            jtxtidRegistro.setText(tablaaceptados.getValueAt(fila_seleccionada, 0).toString());
            jtxtidPeso.setText(tablaaceptados.getValueAt(fila_seleccionada, 3).toString());
            llenaComboConductor(Double.parseDouble(jtxtidPeso.getText()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tablaaceptadosMouseClicked

    private void llenaComboConductor() {
        try {
            rsConductor = objCMConductor.buscarConductorNombre();
            while (rsConductor.next()) {
                jcmbConductor.addItem(rsConductor.getString(2));
            }
        } catch (Exception e) {
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnAnular;
    private javax.swing.JButton jbtnMostarEnvios;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcmbConductor;
    private javax.swing.JTextField jtxtidPeso;
    private javax.swing.JTextField jtxtidRegistro;
    public static javax.swing.JTable tablaaceptados;
    // End of variables declaration//GEN-END:variables

    private void habilitarControles(boolean b) {
        jbtnAceptar.setEnabled(b);
        jbtnAnular.setEnabled(b);
    }

    private void limpiarControles() {
        jDateChooser1.setDate(null);
        jtxtidPeso.setText(null);
        jtxtidRegistro.setText(null);
        jcmbConductor.removeAllItems();
        limpiarJTable();
    }
    
    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) { // RECORRE LA TABLA
            objDtm.removeRow(0);
        }
    }

    private void llenaComboConductor(double peso) {
        try {
            jcmbConductor.removeAllItems();
            rsConductor = objCMConductor.buscarConductor("%");
            while (rsConductor.next()) {                
                String placa = rsConductor.getString(7);
                rsVehiculo = objCMVehiculo.buscarPlaca(placa);
                while (rsVehiculo.next()) {
                    double pesoMaximo = Double.parseDouble(rsVehiculo.getString(9));
                    if(pesoMaximo > peso){
                        jcmbConductor.addItem(rsConductor.getString(4));
                    }                    
                }
            }
            jcmbConductor.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private int obtenerIdConductor() {
        int xidConductor = 0;
        try {
            String nombre = jcmbConductor.getSelectedItem().toString();
            rsConductor.first();
            JOptionPane.showMessageDialog(null,rsConductor.getString(4));
            do {
                
                if (nombre.equals(rsConductor.getString(4))) {
                    xidConductor = rsConductor.getInt(1);
                    rsConductor.last();
                }
            } while (rsConductor.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return xidConductor;
    }
}
