/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.unjfsc.fsi.java8.view;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import pe.unjfsc.fsi.java8.conexion.BDConexion;
import pe.unjfsc.fsi.java8.logical.impl.CMRegistro;

/**
 *
 * @author Hugo Grados
 */
public class JInternalReporteEstados extends javax.swing.JInternalFrame {

    ResultSet rsEstado;
    DefaultTableModel objDtm;
    SimpleDateFormat objSimpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
    CMRegistro objCMRegistro = new CMRegistro();
    boolean sw;

    /**
     * Creates new form JInternalReporteEstados
     */
    public JInternalReporteEstados() {
        initComponents();
        setVisible(true);
        setSize(962, 476);
        objDtm = (DefaultTableModel) jtblRegistros.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jcmbEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jbtnBuscar = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistros = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/array_1.png"))); // NOI18N
        jButton1.setText("GENERAR REPORTE ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 190, 50));

        jcmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "ANULADO", "ACEPTADO" }));
        jcmbEstado.setEnabled(false);
        jcmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("SELECCIONE  ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jbtnBuscar.setText("CONSULTAR");
        jbtnBuscar.setEnabled(false);
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 150, 40));

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registroNuevo.png"))); // NOI18N
        jbtnNuevo.setText("NUEVA CONSULTA");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 240, 40));

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida.png"))); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 110, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ESTADO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("REPORTE FORMULARIO REGISTRADOS - ESTADOS ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jtblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID REGISTRO", "AP CLIENTE", "AM CLIENTE", "PESO", "PAQUETES", "DESCRIPCION", "DPTO PARTIDA", "DPTO LLEGADA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblRegistros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 890, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            String cod = jcmbEstado.getSelectedItem().toString();
            if (cod == "ACEPTADO") {
                Connection cn = BDConexion.getInstance().getConection();
                String direccion = System.getProperty("user.dir") + "\\src\\main\\java\\pe\\unjfsc\\fsi\\java8\\reportes\\EnviosAceptados.jrxml";
                JasperReport reporte = JasperCompileManager.compileReport(direccion);
                Map<String, Object> map = new HashMap<String, Object>();
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporte, map, cn);
                JasperViewer view = new JasperViewer(mostrarReporte, false);
                view.setTitle("Reporte de Envios Aceptados");
                view.setExtendedState(MAXIMIZED_BOTH);
                view.setVisible(true);
            }
            if (cod == "PENDIENTE") {
                Connection cn = BDConexion.getInstance().getConection();
                String direccion = System.getProperty("user.dir") + "\\src\\main\\java\\pe\\unjfsc\\fsi\\java8\\reportes\\EnviosPendientes.jrxml";
                JasperReport reporte = JasperCompileManager.compileReport(direccion);
                Map<String, Object> map = new HashMap<String, Object>();
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporte, map, cn);
                JasperViewer view = new JasperViewer(mostrarReporte, false);
                view.setTitle("Reporte de Envios Pendientes");
                view.setExtendedState(MAXIMIZED_BOTH);
                view.setVisible(true);
            }
            if (cod == "ANULADO") {
                Connection cn = BDConexion.getInstance().getConection();
                String direccion = System.getProperty("user.dir") + "\\src\\main\\java\\pe\\unjfsc\\fsi\\java8\\reportes\\EnviosAnulados.jrxml";
                JasperReport reporte = JasperCompileManager.compileReport(direccion);
                Map<String, Object> map = new HashMap<String, Object>();
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporte, map, cn);
                JasperViewer view = new JasperViewer(mostrarReporte, false);
                view.setTitle("Reporte de Envios Pendientes");
                view.setExtendedState(MAXIMIZED_BOTH);
                view.setVisible(true);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        //
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbEstadoActionPerformed

    }//GEN-LAST:event_jcmbEstadoActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed

        String xidestado = jcmbEstado.getSelectedItem().toString();
        //habilitarControles(false);
        try {

//            String fechaIncio = objSimpleDateFormat.format(jdatInicio.getDate());
//            String fechaFinal = objSimpleDateFormat.format(jdatFinal.getDate());
            if (xidestado == "PENDIENTE") {
                limpiarJTable();
                rsEstado = objCMRegistro.buscar_registros_pendiente();
                while (rsEstado.next()) {
                    Object registro[] = {rsEstado.getInt(1), rsEstado.getString(2), rsEstado.getString(3), rsEstado.getDouble(4), rsEstado.getInt(5),
                        rsEstado.getString(6), rsEstado.getString(7), rsEstado.getString(8)};
                    objDtm.addRow(registro);
                }

            } else if (xidestado == "ACEPTADO") {
                limpiarJTable();
                rsEstado = objCMRegistro.buscar_registros_aceptadosgeneral();
                while (rsEstado.next()) {
                    Object registro[] = {rsEstado.getInt(1), rsEstado.getString(2), rsEstado.getString(3), rsEstado.getDouble(4), rsEstado.getInt(5),
                        rsEstado.getString(6), rsEstado.getString(7), rsEstado.getString(8)};
                    objDtm.addRow(registro);
                }
            }else if (xidestado == "ANULADO") {
                limpiarJTable();
                rsEstado = objCMRegistro.buscar_registros_anulados();
                while (rsEstado.next()) {
                    Object registro[] = {rsEstado.getInt(1), rsEstado.getString(2), rsEstado.getString(3), rsEstado.getDouble(4), rsEstado.getInt(5),
                        rsEstado.getString(6), rsEstado.getString(7), rsEstado.getString(8)};
                    objDtm.addRow(registro);
                }
            }
//            rsEstado = objCLEstado.buscarPorFecha(fechaIncio, fechaFinal, xidestado);
//            while (rsEstado.next()) {
//                Object[] registro = {rsEstado.getInt(1), rsEstado.getString(3), rsEstado.getString(4),
//                    rsEstado.getString(5), rsEstado.getString(6), rsEstado.getString(7), rsEstado.getString(8), rsEstado.getInt(9)};
//                objDtm.addRow(registro);
//
//            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR:" + e);
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        limpiarControles();
        habilitarControles(true);
        sw = true;
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jtblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRegistrosMouseClicked
//        try {
//            int fila_seleccionada = tablaaceptados.getSelectedRow();
//            //LOS DATOS DE LA FILA SELECCIONADA LOS ENVIAMOS A LAS CADENAS DE TEXTO
//            jtxtidRegistro.setText(tablaaceptados.getValueAt(fila_seleccionada, 0).toString());
//            jtxtidPeso.setText(tablaaceptados.getValueAt(fila_seleccionada, 3).toString());
//            llenaComboConductor(Double.parseDouble(jtxtidPeso.getText()));
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e);
//        }
    }//GEN-LAST:event_jtblRegistrosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcmbEstado;
    public static javax.swing.JTable jtblRegistros;
    // End of variables declaration//GEN-END:variables

    private void limpiarControles() {
    }

    private void habilitarControles(boolean b) {
        jbtnBuscar.setEnabled(b);
        jbtnNuevo.setEnabled(!b);
        jcmbEstado.setEnabled(b);
    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) { // RECORRE LA TABLA
            objDtm.removeRow(0);
        }
    }
}
