/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.unjfsc.fsi.java8.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.unjfsc.fsi.java8.entity.CERegistro;
import pe.unjfsc.fsi.java8.logical.impl.CMRegistro;

/**
 *
 * @author Hugo Grados
 */
public class JInternalEnvioPendiente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalEnvioPendiente
     */
    ResultSet rsRegistro;
    DefaultTableModel objDtm;
    CMRegistro objCMRegistro = new CMRegistro();
    boolean sw;
    public JInternalEnvioPendiente() {
        initComponents();
        setVisible(true);
        setSize(953, 450);
        objDtm = (DefaultTableModel) tablapendiente.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablapendiente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbtnMostar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtidRegistro = new javax.swing.JTextField();
        jbtnAnular = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablapendiente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID REGISTRO", "AP CLIENTE", "AM CLIENTE", "PESO", "PAQUETES", "DESCRIPCION", "DPTO PARTIDA", "DPTO LLEGADA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablapendiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablapendienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablapendiente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 900, 160));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ENVIOS EN ESTADO PENDIENTE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jbtnMostar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        jbtnMostar.setText("MOSTRAR ENVIOS");
        jbtnMostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 250, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID ENVIO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jtxtidRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtidRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtidRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 130, 30));

        jbtnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelarRegistro.png"))); // NOI18N
        jbtnAnular.setText("ANULAR");
        jbtnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnularActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 40));

        jbtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar_1.png"))); // NOI18N
        jbtnAceptar.setText("ACEPTAR");
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 340, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida.png"))); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 120, 40));

        jLabel6.setText("BUSCAR POR APELLIDO CLIENTE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jtxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 220, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/limpiar.png"))); // NOI18N
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablapendienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapendienteMouseClicked
        try {
            int fila_seleccionada = tablapendiente.getSelectedRow();
            //LOS DATOS DE LA FILA SELECCIONADA LOS ENVIAMOS A LAS CADENAS DE TEXTO
            jtxtidRegistro.setText(tablapendiente.getValueAt(fila_seleccionada, 0).toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tablapendienteMouseClicked

    private void jbtnMostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostarActionPerformed
        limpiarJTable();
        try {
            rsRegistro = objCMRegistro.buscar_registros_pendiente();
            while (rsRegistro.next()) {
                Object registro[] = {rsRegistro.getInt(1), rsRegistro.getString(2), rsRegistro.getString(3), rsRegistro.getDouble(4), rsRegistro.getInt(5),
                    rsRegistro.getString(6), rsRegistro.getString(7), rsRegistro.getString(8)};
                objDtm.addRow(registro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        habilitarControles(true);
    }//GEN-LAST:event_jbtnMostarActionPerformed

    private void jtxtidRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtidRegistroActionPerformed

    }//GEN-LAST:event_jtxtidRegistroActionPerformed

    private void jbtnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnularActionPerformed
        sw = true;
        try {
            String mensaje = "";
            CERegistro objCERegistro = new CERegistro();
            objCERegistro.setIdRegistro(Integer.parseInt(jtxtidRegistro.getText().toUpperCase()));

            if (sw) {
                objCMRegistro.anular_orden_pendiente(objCERegistro);
                mensaje = "REGISTRO ANULADO";
            } else {             
            }
            JOptionPane.showMessageDialog(rootPane, mensaje);
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jbtnAnularActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        sw = true;
        try {
            String mensaje = "";
            CERegistro objCERegistro = new CERegistro();
            objCERegistro.setIdRegistro(Integer.parseInt(jtxtidRegistro.getText().toUpperCase()));

            if (sw) {
                objCMRegistro.aceptar_orden_pendiente(objCERegistro);
                mensaje = "REGISTRO ACEPTADO";
            } else {
                //                objTecnicoCE.setIdtecnico(Integer.parseInt(jtxtCodigo.getText()));
                //                objCLTecnico.update(objTecnicoCE);
                //                mensaje = "Registro actualizado";
            }
            //            habilitarControles(false);
            JOptionPane.showMessageDialog(rootPane, mensaje);
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyReleased
        try {
            limpiarJTable();
            if (!jtxtBuscar.getText().isEmpty()) {
                rsRegistro = objCMRegistro.buscar_registros_pendiente(jtxtBuscar.getText().trim());
                while (rsRegistro.next()) {
                    Object registro[] = {rsRegistro.getInt(1), rsRegistro.getString(2), rsRegistro.getString(3), rsRegistro.getDouble(4), rsRegistro.getInt(5),
                    rsRegistro.getString(6), rsRegistro.getString(7), rsRegistro.getString(8)};
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtxtBuscarKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiarJTable();
        jtxtBuscar.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnAnular;
    private javax.swing.JButton jbtnMostar;
    private javax.swing.JTextField jtxtBuscar;
    private javax.swing.JTextField jtxtidRegistro;
    public static javax.swing.JTable tablapendiente;
    // End of variables declaration//GEN-END:variables

    private void limpiarControles() {
        jtxtidRegistro.setText(null);
        limpiarJTable();
    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) { // RECORRE LA TABLA
            objDtm.removeRow(0);
        }
    }

    private void habilitarControles(boolean b) {
        jbtnAceptar.setEnabled(b);
        jbtnAnular.setEnabled(b);
    }
}
