/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.unjfsc.fsi.java8.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.unjfsc.fsi.java8.logical.impl.CMVehiculo;

/**
 *
 * @author MIRKO
 */
public class JInternalBuscarVehiculo extends javax.swing.JInternalFrame {
DefaultTableModel objDtm;
    ResultSet rsVehiculo;
    CMVehiculo objVehiculoDAO = new CMVehiculo();
    /**
     * Creates new form JInternalBuscarVehiculo
     */
    public JInternalBuscarVehiculo() {
        initComponents();
        objDtm = (DefaultTableModel) jtblRegistros.getModel();
        setSize(529, 299);
        setLocation(800, 50);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnagregar_vehiculo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtbuscar_vehiculo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistros = new javax.swing.JTable();
        jbtnSalir = new javax.swing.JButton();

        getContentPane().setLayout(null);

        btnagregar_vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registroVehiculo.png"))); // NOI18N
        btnagregar_vehiculo.setText("Agregar vehiculo");
        btnagregar_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_vehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar_vehiculo);
        btnagregar_vehiculo.setBounds(130, 110, 160, 39);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Buscar id vehiculo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 150, 19);

        jtxtbuscar_vehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbuscar_vehiculoKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtbuscar_vehiculo);
        jtxtbuscar_vehiculo.setBounds(240, 60, 160, 22);

        jtblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID vehiculo", "Placa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblRegistros);
        if (jtblRegistros.getColumnModel().getColumnCount() > 0) {
            jtblRegistros.getColumnModel().getColumn(0).setResizable(false);
            jtblRegistros.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 452, 90);

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSalir);
        jbtnSalir.setBounds(310, 110, 90, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtbuscar_vehiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbuscar_vehiculoKeyReleased
      try {
            limpiarJTable();
            if (!jtxtbuscar_vehiculo.getText().isEmpty()) {
                rsVehiculo = objVehiculoDAO.buscar(jtxtbuscar_vehiculo.getText().trim());
                while (rsVehiculo.next()) {
                    Object registro[] = {rsVehiculo.getInt(1), rsVehiculo.getString(2), rsVehiculo.getString(4), rsVehiculo.getString(5), rsVehiculo.getString(7)};
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jtxtbuscar_vehiculoKeyReleased

    private void btnagregar_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_vehiculoActionPerformed
      try {
//            JInternalEnvio.jtxtid_vehiculo.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 0).toString());
//            JInternalEnvio.jtxtplaca.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 1).toString());
           
        } catch (Exception e) {
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnagregar_vehiculoActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
      dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar_vehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JTable jtblRegistros;
    private javax.swing.JTextField jtxtbuscar_vehiculo;
    // End of variables declaration//GEN-END:variables

    private void limpiarJTable() {
         while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    
    }
}
