
package pe.unjfsc.fsi.java8.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.unjfsc.fsi.java8.logical.impl.CMCliente;

/**
 *
 * @author MIRKO
 */
public class JInternalBuscarCliente extends javax.swing.JInternalFrame {
DefaultTableModel objDtm;
    ResultSet rsCliente;
    CMCliente objClienteDAO = new CMCliente();
    /**
     * Creates new form JInternalBuscarCliente
     */
    public JInternalBuscarCliente() {
        initComponents();
        objDtm = (DefaultTableModel) jtblRegistros.getModel();
        setSize(849, 321);
        setLocation(800, 50);
        setVisible(true);
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtbuscar_cliente = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jtblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "NOMBRE", "AP PATERNO", "AP MATERNO", "RUC", "DIRECCION", "TELEFONO", "CELULAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblRegistros);
        if (jtblRegistros.getColumnModel().getColumnCount() > 0) {
            jtblRegistros.getColumnModel().getColumn(0).setResizable(false);
            jtblRegistros.getColumnModel().getColumn(1).setResizable(false);
            jtblRegistros.getColumnModel().getColumn(8).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 800, 90);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Buscar cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 110, 16);

        jtxtbuscar_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbuscar_clienteKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtbuscar_cliente);
        jtxtbuscar_cliente.setBounds(160, 30, 160, 30);

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enviardata.png"))); // NOI18N
        btnagregar.setText("ENVIAR DATA");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar);
        btnagregar.setBounds(350, 20, 140, 50);

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSalir);
        jbtnSalir.setBounds(520, 20, 100, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtbuscar_clienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbuscar_clienteKeyReleased
       try {
            limpiarJTable();
            if (!jtxtbuscar_cliente.getText().isEmpty()) {
                rsCliente = objClienteDAO.buscar(jtxtbuscar_cliente.getText().trim());
                while (rsCliente.next()) {
                    Object registro[] = {rsCliente.getInt(1), rsCliente.getInt(2), rsCliente.getString(3), rsCliente.getString(4), rsCliente.getString(5), rsCliente.getString(6) ,rsCliente.getString(7),
                    rsCliente.getInt(8), rsCliente.getInt(9) };
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jtxtbuscar_clienteKeyReleased

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        try {
            JInternalEnvio.jtxtidCliente.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 0).toString());
            JInternalEnvio.jtxtDniCliente.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 1).toString());
           JInternalEnvio.jtxtNombreCliente.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 2).toString());
           JInternalEnvio.jtxtApellidoPCliente.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 3).toString());
           JInternalEnvio.jtxtApellidoMCliente.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 4).toString());
           JInternalEnvio.jtxtCelularCliente.setText(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 8).toString());
        } catch (Exception e) {
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnagregarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
       dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSalirActionPerformed

     private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JTable jtblRegistros;
    private javax.swing.JTextField jtxtbuscar_cliente;
    // End of variables declaration//GEN-END:variables
}
