/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.unjfsc.fsi.java8.view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.unjfsc.fsi.java8.entity.CETipoVehiculo;
import pe.unjfsc.fsi.java8.logical.impl.CMTipoVehiculo;

/**
 *
 * @author Hugo Grados
 */
public class JInternalTipoCarga extends javax.swing.JInternalFrame {

    boolean sw;
    int xidTipo;
    ResultSet rsTipo;
    DefaultTableModel objDtm;
    CMTipoVehiculo objCMTipo = new CMTipoVehiculo();
    CETipoVehiculo objCETipo = new CETipoVehiculo();
    public JInternalTipoCarga() {
        initComponents();
        setVisible(true);
        setSize(553, 474);
        setTitle("REGISTRO TIPO VEHICULO");
        objDtm = (DefaultTableModel) jtblRegistro.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtnNuevo = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnBorrar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistro = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("BUSCAR TIPOS DE CARGA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jtxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBuscarActionPerformed(evt);
            }
        });
        jtxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 300, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("TIPO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setText("CODIGO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jtxtCodigo.setEditable(false);
        jPanel1.add(jtxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 210, 30));

        jtxtNombre.setEditable(false);
        jtxtNombre.setAutoscrolls(false);
        jPanel1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 480, 160));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registroNuevo.png"))); // NOI18N
        jbtnNuevo.setText("NUEVO");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar.png"))); // NOI18N
        jbtnGuardar.setText("GUARDAR");
        jbtnGuardar.setEnabled(false);
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 40));

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelarRegistro.png"))); // NOI18N
        jbtnCancelar.setText("CANCELAR");
        jbtnCancelar.setEnabled(false);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 40));

        jbtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eliminarVehiculo.png"))); // NOI18N
        jbtnBorrar.setText("ELIMINAR");
        jbtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, 40));

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 130, 40));

        jbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        jbtnEditar.setText("EDITAR");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 480, 110));

        jtblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblRegistroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblRegistro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 480, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBuscarActionPerformed

    private void jtxtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyReleased
        try {
            limpiarJTable();
            if (!jtxtBuscar.getText().isEmpty()) {
                rsTipo = objCMTipo.buscar(jtxtBuscar.getText().trim());
                while (rsTipo.next()) {
                    Object registro[] = {rsTipo.getInt(1), rsTipo.getString(2)};
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtxtBuscarKeyReleased

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        habilitarControles(true);
        limpiarControles();
        sw = true;
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
         try {
            String mensaje = "";
            CETipoVehiculo objTipoCE = new CETipoVehiculo();
            objTipoCE.setNombTipo(jtxtNombre.getText().toUpperCase());
            objTipoCE.setIdTipo(xidTipo);
            if (sw) {
                objCMTipo.insert(objTipoCE);
                mensaje = "Registro grabado";
            } else {
                objTipoCE.setIdTipo(Integer.parseInt(jtxtCodigo.getText()));
                objCMTipo.update(objTipoCE);
                mensaje = "Registro actualizado";
            }
            habilitarControles(false);
            JOptionPane.showMessageDialog(rootPane, mensaje);
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBorrarActionPerformed
        try {
            int op = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea eliminar?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (op == JOptionPane.YES_OPTION) {
                CETipoVehiculo objTipo = new CETipoVehiculo();
                objTipo.setIdTipo(Integer.parseInt(jtxtCodigo.getText()));
                objCMTipo.delete(objTipo);
                limpiarControles();
                JOptionPane.showMessageDialog(rootPane, "Registro Borrado");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtnBorrarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        habilitarControles(true);
        sw = false;
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jtblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRegistroMouseClicked
        int fila_seleccionada = jtblRegistro.getSelectedRow();
        //LOS DATOS DE LA FILA SELECCIONADA LOS ENVIAMOS A LAS CADENAS DE TEXTO
        jtxtCodigo.setText(jtblRegistro.getValueAt(fila_seleccionada, 0).toString());
        jtxtNombre.setText(jtblRegistro.getValueAt(fila_seleccionada, 1).toString());
    }//GEN-LAST:event_jtblRegistroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBorrar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JTable jtblRegistro;
    private javax.swing.JTextField jtxtBuscar;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) { // RECORRE LA TABLA
            objDtm.removeRow(0);
        }
    }

    private void habilitarControles(boolean b) {
        jtxtNombre.setEditable(b);
        jtxtBuscar.setEditable(!b);
        jbtnEditar.setEnabled(!b);
        jbtnSalir.setEnabled(!b);
        jbtnNuevo.setEnabled(!b);
        jbtnBorrar.setEnabled(!b);
        jbtnGuardar.setEnabled(b);
        jbtnCancelar.setEnabled(b);
        jtxtNombre.grabFocus();
    }

    private void limpiarControles() {
        limpiarJTable();
        jtxtBuscar.setText(null);
        jtxtCodigo.setText(null);
        jtxtNombre.setText(null);
    }
}
