/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.unjfsc.fsi.java8.view;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.unjfsc.fsi.java8.entity.CERegistroAsig;
import pe.unjfsc.fsi.java8.logical.impl.CMRegistro;
import pe.unjfsc.fsi.java8.logical.impl.CMRegistroFinal;

/**
 *
 * @author Koraima
 */
public class JInternalEnvioFinalizado extends javax.swing.JInternalFrame {
    
    ResultSet rsRegistro;
    DefaultTableModel objDtm;
    CMRegistro objCMRegistro = new CMRegistro();
    CMRegistroFinal objCMRegistroFinal = new CMRegistroFinal();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    
    boolean sw;
    int xidRegistro;
    int xidConductor;

    /**
     * Creates new form JInternalEnvioFinalizado
     */
    public JInternalEnvioFinalizado() {
        initComponents();
        objDtm = (DefaultTableModel) tablaFinalizados.getModel();
        setVisible(true);
        setSize(962, 447);
        setTitle("FINALIZAR ENVIOS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnMostarEnvios = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtnAnular = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();
        jtxtidRegistro = new javax.swing.JTextField();
        jbtnSalir = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFinalizados = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("FINALIZAR ENVIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jbtnMostarEnvios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        jbtnMostarEnvios.setText("MOSTRAR ENVIOS");
        jbtnMostarEnvios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostarEnviosActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMostarEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 240, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("FECHA DE LLEGADA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 110, 20));

        jbtnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelarRegistro.png"))); // NOI18N
        jbtnAnular.setText("CANCELAR");
        jbtnAnular.setEnabled(false);
        jbtnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnularActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 140, 50));

        jbtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar_1.png"))); // NOI18N
        jbtnAceptar.setText("FINALIZAR");
        jbtnAceptar.setEnabled(false);
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 130, 50));
        jPanel1.add(jtxtidRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 60, 30));

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida.png"))); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 160, 50));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 250, -1));

        jLabel4.setText("ID REGISTRO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 890, 150));

        jLabel5.setText("CONFIRMACIÓN DE FECHA DE LLEGADA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        tablaFinalizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID REGISTRO", "AP CLIENTE", "AM CLIENTE", "PESO", "PAQUETES", "DESCRIPCION", "DPTO PARTIDA", "DPTO LLEGADA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFinalizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaFinalizadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaFinalizados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 890, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMostarEnviosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostarEnviosActionPerformed
        limpiarJTable();
        try {
            
            rsRegistro = objCMRegistroFinal.buscar(ABORT);
            while (rsRegistro.next()) {
                Object registro[] = {rsRegistro.getInt(1), rsRegistro.getString(2), rsRegistro.getString(3), rsRegistro.getDouble(4), rsRegistro.getInt(5),
                    rsRegistro.getString(6), rsRegistro.getString(7), rsRegistro.getString(8)};
                objDtm.addRow(registro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
        habilitarControles(true);
    }//GEN-LAST:event_jbtnMostarEnviosActionPerformed

    private void jbtnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnularActionPerformed
        habilitarControles(false);
        limpiarControles();
    }//GEN-LAST:event_jbtnAnularActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed
        sw = true;
        try {
            String mensaje = "";
            CERegistroAsig objCERegistroAsig = new CERegistroAsig();
            objCERegistroAsig.setIdRegistro(Integer.parseInt(jtxtidRegistro.getText().toUpperCase()));
            java.util.Date fecha = (jDateChooser1.getDate());
            java.sql.Date fechaLlegada = new java.sql.Date(fecha.getTime());
            objCERegistroAsig.setFechaLlegada(fechaLlegada);
            objCMRegistroFinal.set_fecha_llegada(jtxtidRegistro.getText(), sdf.format(fechaLlegada));
            mensaje = "ENVIO FINALIZADO";
            JOptionPane.showMessageDialog(this, mensaje);
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
            
        }
    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void tablaFinalizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFinalizadosMouseClicked
        try {
            int fila_seleccionada = tablaFinalizados.getSelectedRow();
            //LOS DATOS DE LA FILA SELECCIONADA LOS ENVIAMOS A LAS CADENAS DE TEXTO
            jtxtidRegistro.setText(tablaFinalizados.getValueAt(fila_seleccionada, 0).toString());            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tablaFinalizadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnAnular;
    private javax.swing.JButton jbtnMostarEnvios;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JTextField jtxtidRegistro;
    public static javax.swing.JTable tablaFinalizados;
    // End of variables declaration//GEN-END:variables

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) { // RECORRE LA TABLA
            objDtm.removeRow(0);
        }
    }
    
    private void habilitarControles(boolean b) {
        jbtnAceptar.setEnabled(b);
        jbtnAnular.setEnabled(b);
    }
    
    private void limpiarControles() {
        jDateChooser1.setDate(null);
        jtxtidRegistro.setText(null);
        limpiarJTable();
    }
    
}
